version: "3.2"

services:
    proxy:
        image: ${IDP_PROXY_IMAGE}
        environment:
          TZ: Asia/Kolkata
        volumes:
            - ${MOUNT_DIR}/proxy/idp.conf:/etc/nginx/conf.d/default.conf
            - ${MOUNT_DIR}/proxy/nginx.conf:/etc/nginx/nginx.conf
            - ${MOUNT_DIR}/proxy/addon_config/:/addon_config/
        deploy:
          mode: replicated
          replicas: 1

    zookeeper:
        image: ${IDP_ZOOKEEPER_IMAGE}
        environment:
          TZ: Asia/Kolkata
        deploy:
          mode: replicated
          replicas: 1
    kafka:
        image: ${IDP_KAFKA_IMAGE}
        environment:
          TZ: Asia/Kolkata
          KAFKA_BROKER_ID: 1001
          KAFKA_RESERVED_BROKER_MAX_ID: 1001
          HOSTNAME_COMMAND: "echo ${KAFKA_HOSTNAME}"      
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
          KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
          KAFKA_ADVERTISED_PORT: ${KAFKA_PORT}
          KAFKA_PROTOCOL_NAME: INSIDE
          KAFKA_PORT: 9091
        deploy:
          mode: replicated
          replicas: 1
    postgres:
        image: ${IDP_POSTGRES_IMAGE}
        environment:
            POSTGRES_DB: ${POSTGRES_DEFAULT}
            POSTGRES_USER: ${POSTGRES_USER}
            SESSION_SECRET: ${POSTGRES_PASSWORD}
            TZ: Asia/Kolkata          
        volumes:
            - ${MOUNT_DIR}/postgresdata/:/var/lib/postgresql/data/
            - ${MOUNT_DIR}/postgresinit/:/docker-entrypoint-initdb.d/ 
        deploy:
          mode: replicated
          replicas: 1
    keycloak:
        image: ${IDP_KEYCLOAK_IMAGE}
        environment:
          TZ: Asia/Kolkata
          KEYCLOAK_USER: ${KEYCLOAK_USER}
          KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
          POSTGRES_ADDR: ${POSTGRES_HOSTNAME}
          POSTGRES_DATABASE: ${POSTGRES_DEFAULT}
          POSTGRES_PORT: ${POSTGRES_PORT} 
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          PROXY_ADDRESS_FORWARDING: "true"
        deploy:
          mode: replicated
          replicas: 1
    grafana:
        image: ${IDP_GRAFANA_IMAGE}
        environment:
          TZ: Asia/Kolkata
          GRAFANA_PROTOCOL: "${PROTOCOL}"
          ADMIN_PASSWORD: idp@123
          KEYCLOAK_URL: "${PROTOCOL}://${KEYCLOAK_HOSTNAME}${KEYCLOAK_PORT}"
          KEYCLOAK_REALM: master
          GRAFANA_HOSTNAME: ${GRAFANA_HOSTNAME}
          GRAFANA_PORT: ${GRAFANA_PORT}
        volumes:
            - ${MOUNT_DIR}/grafanadata/grafana.ini:/etc/grafana/grafana.ini
            - ${MOUNT_DIR}/grafanadata/data/plugins:/var/lib/grafana/plugins
            - ${MOUNT_DIR}/grafanadata/data/dashboards:/var/lib/grafana/dashboards
            - ${MOUNT_DIR}/grafanadata/provisioning/:/etc/grafana/provisioning/
        deploy:
          mode: replicated
          replicas: 1

    jenkins:
        image: ${IDP_JENKINS_IMAGE}
        ports:
            - ${JENKINS_SLAVE_PORT}:${JENKINS_SLAVE_PORT}
        environment:
          TZ: Asia/Kolkata
          JENKINS_HOME: /var/jenkins_home/
        volumes:
            - ${MOUNT_DIR}/server.xml:/usr/local/tomcat/conf/server.xml
            - ${MOUNT_DIR}/jenkinsdata:/var/jenkins_home/
            - ${MOUNT_DIR}/dsldata:/DSL/
        deploy:
          mode: replicated
          replicas: 1
    config:
        image: ${IDP_CONFIG_IMAGE}
        environment:
          TZ: Asia/Kolkata
          CONFIG_USERNAME: ${CONFIG_USERNAME}
          CONFIG_PASSWORD: ${CONFIG_PASSWORD}
          SSL_ENABLED: ${SSL_ENABLED}
        deploy:
          mode: replicated
          replicas: 1
    eureka:
        image: ${IDP_EUREKA_IMAGE}
        environment:
          TZ: Asia/Kolkata
          SSL_ENABLED: ${SSL_ENABLED}
        deploy:
          mode: replicated
          replicas: 1
    oauth:
        image: ${IDP_OAUTH_IMAGE}
        environment:
          TZ: Asia/Kolkata
          PROFILE: ${PROFILE}
          KAFKA_HOSTNAME: ${KAFKA_HOSTNAME}
          KAFKA_PORT: ${KAFKA_PORT}
          CONFIG_HOSTNAME: ${CONFIG_HOSTNAME}
          CONFIG_PORT: ${CONFIG_PORT}
          CONFIG_USERNAME: ${CONFIG_USERNAME}
          CONFIG_PASSWORD: ${CONFIG_PASSWORD}
          POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME}
          KEYCLOAK_PORT: ${KEYCLOAK_PORT}
          KEYCLOAK_USER: ${KEYCLOAK_USER}
          KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
          AUTH_PROVIDER: ${AUTH_PROVIDER}
          LDAP_URL: ${LDAP_URL}
          SMTP_DOMAIN: ${SMTP_DOMAIN}          
          SSL_ENABLED: ${SSL_ENABLED}
        deploy:
          mode: replicated
          replicas: 1
    services:
        image: ${IDP_SERVICES_IMAGE}
        environment:
          TZ: Asia/Kolkata
          PROFILE: ${PROFILE}
          GRAFANA_HOSTNAME: ${GRAFANA_HOSTNAME}
          GRAFANA_PORT: ${GRAFANA_PORT}
          ZOOKEEPER_HOSTNAME: ${ZOOKEEPER_HOSTNAME}
          ZOOKEEPER_PORT: ${ZOOKEEPER_PORT}
          KAFKA_HOSTNAME: ${KAFKA_HOSTNAME}
          KAFKA_PORT: ${KAFKA_PORT}
          CONFIG_HOSTNAME: ${CONFIG_HOSTNAME}
          CONFIG_PORT: ${CONFIG_PORT}
          CONFIG_USERNAME: ${CONFIG_USERNAME}
          CONFIG_PASSWORD: ${CONFIG_PASSWORD}
          EUREKA_HOSTNAME: ${EUREKA_HOSTNAME}
          EUREKA_PORT: ${EUREKA_PORT}
          SCHEDULER_HOSTNAME: ${SCHEDULER_HOSTNAME}
          SCHEDULER_PORT: ${SCHEDULER_PORT}
          POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_DEFAULT: ${POSTGRES_DEFAULT}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME}
          KEYCLOAK_PORT: ${KEYCLOAK_PORT}
          KEYCLOAK_USER: ${KEYCLOAK_USER}
          KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
          JENKINS_HOSTNAME: ${JENKINS_HOSTNAME}
          JENKINS_PORT: ${JENKINS_PORT}
          JENKINS_USERNAME: ${JENKINS_USERNAME}
          JENKINS_PASSWORD: ${JENKINS_PASSWORD}
          OAUTH_HOSTNAME: ${OAUTH_HOSTNAME}
          OAUTH_PORT: ${OAUTH_PORT}
          DASHBOARD_HOSTNAME: ${DASHBOARD_HOSTNAME}
          DASHBOARD_PORT: ${DASHBOARD_PORT}
          IDPAPP_HOSTNAME: ${IDPAPP_HOSTNAME}
          IDPAPP_PORT: ${IDPAPP_PORT}
          SUBSCRIPTION_HOSTNAME: ${SUBSCRIPTION_HOSTNAME}
          SUBSCRIPTION_PORT: ${SUBSCRIPTION_PORT}
          SERVICES_HOSTNAME: ${SERVICES_HOSTNAME}
          SERVICES_PORT: ${SERVICES_PORT}
          SSL_ENABLED: ${SSL_ENABLED}
        deploy:
          mode: replicated
          replicas: 1
    dashboard:
        image: ${IDP_DASHBOARD_IMAGE}
        environment:
          TZ: Asia/Kolkata
          PROFILE: ${PROFILE}
          KAFKA_HOSTNAME: ${KAFKA_HOSTNAME}
          KAFKA_PORT: ${KAFKA_PORT}
          SERVICES_HOSTNAME: ${SERVICES_HOSTNAME}
          SERVICES_PORT: ${SERVICES_PORT}
          CONFIG_HOSTNAME: ${CONFIG_HOSTNAME}
          CONFIG_PORT: ${CONFIG_PORT}
          CONFIG_USERNAME: ${CONFIG_USERNAME}
          CONFIG_PASSWORD: ${CONFIG_PASSWORD}
          POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_DEFAULT: ${POSTGRES_DEFAULT}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          JENKINS_HOSTNAME: ${JENKINS_HOSTNAME}
          JENKINS_PORT: ${JENKINS_PORT}
          JENKINS_USERNAME: ${JENKINS_USERNAME}
          JENKINS_PASSWORD: ${JENKINS_PASSWORD}
          SSL_ENABLED: ${SSL_ENABLED}
        deploy:
          mode: replicated
          replicas: 1
    app:
        image: ${IDP_UI_IMAGE}
        environment:
          TZ: Asia/Kolkata
          PROFILE: ${PROFILE}
          GRAFANA_HOSTNAME: ${GRAFANA_HOSTNAME}
          GRAFANA_PORT: ${GRAFANA_PORT}
          CONFIG_HOSTNAME: ${CONFIG_HOSTNAME}
          CONFIG_PORT: ${CONFIG_PORT}
          CONFIG_USERNAME: ${CONFIG_USERNAME}
          CONFIG_PASSWORD: ${CONFIG_PASSWORD}
          OAUTH_HOSTNAME: ${OAUTH_HOSTNAME}
          OAUTH_PORT: ${OAUTH_PORT}
          DASHBOARD_HOSTNAME: ${DASHBOARD_HOSTNAME}
          DASHBOARD_PORT: ${DASHBOARD_PORT}
          IDPAPP_HOSTNAME: ${IDPAPP_HOSTNAME}
          IDPAPP_PORT: ${IDPAPP_PORT}
          SUBSCRIPTION_HOSTNAME: ${SUBSCRIPTION_HOSTNAME}
          SUBSCRIPTION_PORT: ${SUBSCRIPTION_PORT}
          SERVICES_HOSTNAME: ${SERVICES_HOSTNAME}
          SERVICES_PORT: ${SERVICES_PORT}
          KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME}
          KEYCLOAK_PORT: ${KEYCLOAK_PORT}
          
          CLOUD_DEPLOY_FLAG: ${CLOUD_DEPLOY_FLAG}
          HIDE_JSON_CONVERT: ${HIDE_JSON_CONVERT}
          SSL_ENABLED: ${SSL_ENABLED}
        deploy:
          mode: replicated
          replicas: 1
    subscription:
        image: ${IDP_SUBSCRIPTION_IMAGE}
        environment:
          TZ: Asia/Kolkata
          PROFILE: ${PROFILE}
          GRAFANA_HOSTNAME: ${GRAFANA_HOSTNAME}
          GRAFANA_PORT: ${GRAFANA_PORT}
          KAFKA_HOSTNAME: ${KAFKA_HOSTNAME}
          KAFKA_PORT: ${KAFKA_PORT}
          CONFIG_HOSTNAME: ${CONFIG_HOSTNAME}
          CONFIG_PORT: ${CONFIG_PORT}
          CONFIG_USERNAME: ${CONFIG_USERNAME}
          CONFIG_PASSWORD: ${CONFIG_PASSWORD}
          EUREKA_HOSTNAME: ${EUREKA_HOSTNAME}
          EUREKA_PORT: ${EUREKA_PORT}
          SCHEDULER_HOSTNAME: ${SCHEDULER_HOSTNAME}
          SCHEDULER_PORT: ${SCHEDULER_PORT}
          POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_DEFAULT: ${POSTGRES_DEFAULT}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME}
          KEYCLOAK_PORT: ${KEYCLOAK_PORT}
          KEYCLOAK_USER: ${KEYCLOAK_USER}
          KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
          JENKINS_HOSTNAME: ${JENKINS_HOSTNAME}
          JENKINS_PORT: ${JENKINS_PORT}
          JENKINS_USERNAME: ${JENKINS_USERNAME}
          JENKINS_PASSWORD: ${JENKINS_PASSWORD}
          OAUTH_HOSTNAME: ${OAUTH_HOSTNAME}
          OAUTH_PORT: ${OAUTH_PORT}
          DASHBOARD_HOSTNAME: ${DASHBOARD_HOSTNAME}
          DASHBOARD_PORT: ${DASHBOARD_PORT}
          IDPAPP_HOSTNAME: ${IDPAPP_HOSTNAME}
          IDPAPP_PORT: ${IDPAPP_PORT}
          SUBSCRIPTION_HOSTNAME: ${SUBSCRIPTION_HOSTNAME}
          SUBSCRIPTION_PORT: ${SUBSCRIPTION_PORT}
          SERVICES_HOSTNAME: ${SERVICES_HOSTNAME}
          SERVICES_PORT: ${SERVICES_PORT}
          SSL_ENABLED: ${SSL_ENABLED}
        deploy:
          mode: replicated
          replicas: 1
    scheduler:
        image: ${IDP_SCHEDULER_IMAGE}
        environment:
          TZ: Asia/Kolkata
          PROFILE: ${PROFILE}
          GRAFANA_HOSTNAME: ${GRAFANA_HOSTNAME}
          GRAFANA_PORT: ${GRAFANA_PORT}
          ZOOKEEPER_HOSTNAME: ${ZOOKEEPER_HOSTNAME}
          ZOOKEEPER_PORT: ${ZOOKEEPER_PORT}
          KAFKA_HOSTNAME: ${KAFKA_HOSTNAME}
          KAFKA_PORT: ${KAFKA_PORT}
          CONFIG_HOSTNAME: ${CONFIG_HOSTNAME}
          CONFIG_PORT: ${CONFIG_PORT}
          CONFIG_USERNAME: ${CONFIG_USERNAME}
          CONFIG_PASSWORD: ${CONFIG_PASSWORD}
          EUREKA_HOSTNAME: ${EUREKA_HOSTNAME}
          EUREKA_PORT: ${EUREKA_PORT}
          SCHEDULER_HOSTNAME: ${SCHEDULER_HOSTNAME}
          SCHEDULER_PORT: ${SCHEDULER_PORT}
          POSTGRES_HOSTNAME: ${POSTGRES_HOSTNAME}
          POSTGRES_PORT: ${POSTGRES_PORT}
          POSTGRES_DEFAULT: ${POSTGRES_DEFAULT}
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME}
          KEYCLOAK_PORT: ${KEYCLOAK_PORT}
          KEYCLOAK_USER: ${KEYCLOAK_USER}
          KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
          JENKINS_HOSTNAME: ${JENKINS_HOSTNAME}
          JENKINS_PORT: ${JENKINS_PORT}
          JENKINS_USERNAME: ${JENKINS_USERNAME}
          JENKINS_PASSWORD: ${JENKINS_PASSWORD}
          OAUTH_HOSTNAME: ${OAUTH_HOSTNAME}
          OAUTH_PORT: ${OAUTH_PORT}
          DASHBOARD_HOSTNAME: ${DASHBOARD_HOSTNAME}
          DASHBOARD_PORT: ${DASHBOARD_PORT}
          IDPAPP_HOSTNAME: ${IDPAPP_HOSTNAME}
          IDPAPP_PORT: ${IDPAPP_PORT}
          SUBSCRIPTION_HOSTNAME: ${SUBSCRIPTION_HOSTNAME}
          SUBSCRIPTION_PORT: ${SUBSCRIPTION_PORT}
          SERVICES_HOSTNAME: ${SERVICES_HOSTNAME}
          SERVICES_PORT: ${SERVICES_PORT}
          SSL_ENABLED: ${SSL_ENABLED}
        deploy:
          mode: replicated
          replicas: 1

    
