version: "3.2"

services:
    proxy:
        ports:
            - ${CUSTOM_PORT}:${CUSTOM_PORT}
        volumes:
            - ${MOUNT_DIR}/proxy/ssl.conf:/protocol_config/protocol.conf
            - ${MOUNT_DIR}/certs/:/certs/
    config:
        environment:
          SSL_CA_LOC: ${SSL_CA_LOC}
        volumes:
            - ${MOUNT_DIR}/certs/:/certs/
    eureka:
        environment:
          SSL_CA_LOC: ${SSL_CA_LOC}
        volumes:
            - ${MOUNT_DIR}/certs/:/certs/
    oauth:
        environment:
          SSL_CA_LOC: ${SSL_CA_LOC}
        volumes:
            - ${MOUNT_DIR}/certs/:/certs/
    services:
        environment:
          SSL_CA_LOC: ${SSL_CA_LOC}
        volumes:
            - ${MOUNT_DIR}/certs/:/certs/
    dashboard:
        environment:
          SSL_CA_LOC: ${SSL_CA_LOC}
        volumes:
            - ${MOUNT_DIR}/certs/:/certs/
    app:
        environment:
          SSL_CA_LOC: ${SSL_CA_LOC}
        volumes:
            - ${MOUNT_DIR}/certs/:/certs/
    subscription:
        environment:
          SSL_CA_LOC: ${SSL_CA_LOC}
        volumes:
            - ${MOUNT_DIR}/certs/:/certs/
    scheduler:
        environment:
          SSL_CA_LOC: ${SSL_CA_LOC}
        volumes:
            - ${MOUNT_DIR}/certs/:/certs/
